export const printInvoice = (cart, subtotal) => {
  const printWindow = window.open("", "_blank", "height=600, width=800");
  printWindow.document.write(`
      <html>
        <head>
          <title>Sales Invoice</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            .header { text-align: center; margin-bottom: 20px; }
            .header h1 { margin: 0; }
            .items { width: 100%; border-collapse: collapse; margin-top: 20px; }
            .items th, .items td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            .items th { background-color: #f4f4f4; }
            .totals { margin-top: 20px; text-align: right; }
            .totals p { margin: 0; }
            .footer { text-align: center; margin-top: 30px; font-size: 14px; }
          </style>
        </head>
        <body>
       <div style="text-align: center;">
  <img src="https://t3.ftcdn.net/jpg/02/84/04/04/360_F_284040432_qoTl3CyZQRgFoAb9wy9iT03xoLKxfFtM.jpg" 
       style="width: 150px; height: auto;" 
       alt="Company Logo" />
</div>
          <div class="header">
            <p>123 Main Street, colombo 7, sri lanka</p>
            <p>Email: hello@pizza.com | Phone: +123456789</p>
          </div>
          <h2>Invoice</h2>
          <table class="items">
            <thead>
              <tr>
                <th>Item</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              ${cart
                .map(
                  (item) => `
                  <tr>
                    <td>${item.Name}</td>
                    <td>${item.Quantity}</td>
                    <td>Rs. ${item.Price}</td>
                    <td>Rs. ${item.Price * item.Quantity}</td>
                  </tr>
                `
                )
                .join("")}
            </tbody>
          </table>
          <div class="totals">
            <p>Subtotal: Rs. ${subtotal.toFixed(2)}</p>
            <p>Tax (10%): Rs. ${(subtotal * 0.1).toFixed(2)}</p>
            <h3>Total: Rs. ${(subtotal + subtotal * 0.1).toFixed(2)}</h3>
          </div>
          <div class="footer">
            <p>Thank you for your purchase!</p>
            <p>Invoice generated by Pizza Shop</p>
          </div>
        </body>
      </html>
    `);
  printWindow.document.close();
  printWindow.print();
};
